# Generated by Django 4.1.7 on 2023-03-26 09:59

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfile',
            name='path',
        ),
        migrations.AddField(
            model_name='modelfile',
            name='model_obj',
            field=models.FileField(null=True, upload_to=pathlib.PureWindowsPath('D:/Projectz/machine-learning-project/backend/static/media/saved_models')),
        ),
    ]
